language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install coveralls
  - pip install pyrodeo

# command to run tests
script: coverage run --source=pyrodeo setup.py test

after_success:
  - coveralls
